version: "3"

services:
  identity-server1:
    image: test-identity-server:latest
    hostname: identity-server1
    container_name: identity-server1
    ports:
      - "5000:80"

  identity-server2:
    image: test-identity-server:latest
    hostname: identity-server2
    container_name: identity-server2
    ports:
      - "5001:80"
